version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
#     - npm install -g serverless
#     - npm test
  post_build:
    commands:
      - serverless deploy --region us-east-2