version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm install -g serverless
#     - npm test
  build:
    commands:
      - serverless deploy --stage cicd --region us-east-2 | tee deploy.out
  post_build:
    commands:
      - . ./test.sh