version: 0.2
environment_variables:
  plaintext:
      "INPUT_FILE": "serverless.yml"
      "S3_BUCKET": ""
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install -g serverless
#     - npm test
  post_build:
    commands:
      - serverless deploy